name: zerotier_sockets
description: libzt bindings for Flutter
version: 1.0.0
repository: https://github.com/nuc134r/zerotier_sockets_flutter

environment:
  sdk: '>=2.19.5 <3.0.0'
  flutter: ">=2.11.0"

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  ffigen: ^7.2.11
  test: ^1.20.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
